services:
  db:
    image: mysql:8
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
  s3:
    image: localstack/localstack
    platform: linux/amd64
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
  utils:
    build: .
    platform: linux/amd64
    volumes:
      - ./tests:/root/bin
    command: /root/bin/tests.sh
    depends_on:
      - db
      - s3
    environment:
      DATABASE_URL: mysql://test:password@db:3306/test
      AWS_ENDPOINT_URL: http://s3:4566
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
