name: Test Postgres

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test Postgres
        run: |
          docker-compose -f docker-compose.test.yml run --rm utils
          docker-compose -f docker-compose.test.yml down
        working-directory: postgres
      - name: Test Postgres v13
        run: PG_VERSION=13 docker-compose -f docker-compose.test.yml run --rm utils
        working-directory: postgres
