name: Test Postgres

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test Postgres
      run: |
        cd postgres
        docker-compose -f docker-compose.test.yml run --rm utils
